# ========== 应用基本配置 ==========
# 应用名称
server:
  port: 9090

#输出到控制台

spring:
#  使用Logback作为日志框架
  profiles:
    active: dev


  security:
    user:
      name: admin
      password: 123456
  # ========== 数据源配置（可选，初始化数据库时使用）==========
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3307/strange-loop?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: StrangeLoop


  # 编码配置
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    banner-mode: off


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

# ========== 日志配置 ==========
# 日志输出级别（可选：TRACE, DEBUG, INFO, WARN, ERROR）
logging:

  level:
    root: INFO
    com.example.demo: DEBUG
  # 日志文件位置（默认在控制台输出）
  # file:
  #   name: logs/demo-app.log
  #   path: logs


  # JPA 配置（如果使用 Spring Data JPA）




# MyBatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.xiaofeng.strangeloop.system.domain.*
  configuration:
    map-underscore-to-camel-case: true
